### ISSUE TITLE
Can't play Artist Top Songs

### ISSUE THREAD

**Issue by furacao14** [amp64/sonosbugtracker#17] opened 2024-08-07 23:57 UTC
I can search for an Artist and see their Top Songs folder, but there's no option to play these songs. If I click on one of these songs it plays only this one and stops.

**Comment by amp64** [comment] 2024-08-08 14:00
Which music service is this with? Sounds like it might be a dupe of #12

**Comment by furacao14** [comment] 2024-08-08 14:34
Amazon Music, but you're right. It's a dupe of #12, so I'm closing this

**Closed as completed** 2024-08-08 14:38 UTC
Labels: bug
